### ISSUE TITLE
Tracking the result of td.GetChats() and td.LoadChats()

### ISSUE THREAD

**Issue by Yaroslav-Zagumennikov** [ivk1800/tdlib-dart#15]
I had a problem when I was trying to track the result of a query
_client?.send(const td.GetChats(limit: 10))

![image](https://github.com/ivk1800/tdlib-dart/assets/91648112/a345854e-ef85-4078-9234-1904a3054892)

I used the following code to track the result, but the value of the variable is still empty
I changed the code of the example file

![image](https://github.com/ivk1800/tdlib-dart/assets/91648112/bebbeee6-238f-49a1-b15f-ec3956166825)
![image](https://github.com/ivk1800/tdlib-dart/assets/91648112/4e2ea780-cc4c-4ce6-b272-5e7faf27d9c6)
```dart
if (_chats.isNotEmpty)
              Expanded(
                child: ListView.builder(
                  itemCount: _chats.length,
                  itemBuilder: (context, index) {
                    final chat = _chats[index];
                    return ListTile(
                      title: Text(chat.title ?? ''),
                      subtitle: Text(chat.type.toString()),
                    );
                  },
                ),
              ),
```

**Comment by ivk1800** [comment]
Please check working example: https://github.com/ivk1800/telegram-flutter/blob/a1093fc75043c9c2b4e53fb986971b2014fc7f3a/core_tdlib_impl/lib/src/data_source/chat_data_source.dart#L72
