### ISSUE TITLE
1.8.26 null pointer exception crash

### ISSUE THREAD

**Issue by JrAnTran** [ivk1800/tdlib-dart#18]
![Screenshot from 2024-05-09 00-13-23](https://github.com/ivk1800/tdlib-dart/assets/169292674/1f01217a-52ee-412b-bf15-f896cac4b41d)
@ivk1800 

Please help check!
Configuration:
tdlib-dart
| 1.8.26  |                          last commit                          |   [b1b33cf](https://github.com/tdlib/td/blob/b1b33cf/td/generate/scheme/td_api.tl) |

Andrdoi prebuilt:
https://github.com/ivk1800/td-json-client-prebuilt/releases/download/android-1.8.26-b1b33cf/libs.zip

**Comment by ivk1800** [comment]
Fixed in https://github.com/ivk1800/tdlib-dart/commit/d52eb0540ea3b77a8614300bc8c827335cb8b1af
