### ISSUE TITLE
 InlineKeyboardButton hit  with tdlib API

### ISSUE THREAD

**Issue by JrAnTran** [ivk1800/tdlib-dart#20]
Hello @ivk1800 

I need to simulate InlineKeyboardButton hit from my app. Digging around the internet, there is a few of things related such as GetBotCallbackAnswerRequest...

Could you please help clarify this. Many thanks.

I found this. Looks like always using sendMessage with inline button data?
$inline[] = [['text'=>tgescape($row['text']), 'web_app' => ['url' => $row['val']]]];
$inline = '{"inline_keyboard":'.json_encode($inline).'}';
sendMsg($bot['token'],$chatId,"Нажмите для запуска:", ["reply_markup"=>$inline]);

**Comment by JrAnTran** [comment]
@ivk1800
 in an attempt to openWebApp via hit inlinekeyboadbutton simualtion, I call openWebApp, but its returns "Bot not found"

![Screenshot from 2024-05-10 18-55-05](https://github.com/ivk1800/tdlib-dart/assets/169292674/d7ecaf80-e9a8-499c-babf-48c583801ee2)

**Comment by ivk1800** [comment]
Such questions would be better answered in the [td](https://github.com/tdlib/td) repository, I am not qualified to answer this
