### ISSUE TITLE
Unhandled Exception: 'package:tdlib/src/client/platform/io/io_platform.dart': Failed assertion: line 60 pos 12: '_client != null': is not true.

### ISSUE THREAD

**Issue by Mashi-91** [ivk1800/tdlib-dart#21]
Showing this error Anyone....

Unhandled Exception: 'package:tdlib/src/client/platform/io/io_platform.dart': Failed assertion: line 60 pos 12: '_client != null': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      PlatformImpl.send (package:tdlib/src/client/platform/io/io_platform.dart:60:12)
#3      ClientImpl.send (package:tdlib/src/client/client_impl.dart:32:16)
#4      NavigationScreenDesktopTablet.build.<anonymous closure> (package:CloudInfinity/screens/desktop/home/navigation_screen_desktop_tablet.dart:40:56)
#5      ScreensWidgets.buildFloatingActionButton.<anonymous closure> (package:CloudInfinity/screens/widgets/screen_widgets.dart:126:35)
#6      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1183:21)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:315:24)
#8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652:11)
#9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309:5)
#10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:242:7)
#11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:670:9)
#12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:495:19)
#18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
#19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:430:11)
#20     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
#21     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
#22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
#23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
#24     _invoke1 (dart:ui/hooks.dart:328:13)
#25     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:429:7)
#26     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)

**Comment by stellarNuke** [comment]
Fixed it created a pull request hope he is active.

**Comment by Mashi-91** [comment]
Ok let me check

**Comment by Mashi-91** [comment]
Actually bro I already solved tht problem.. 😝
