### ISSUE TITLE
Problem with sendStory

### ISSUE THREAD

**Issue by wudb** [ivk1800/tdlib-dart#28]
Hello, 
When I want to publish the story, there is a problem using the sendStory function: How to transfer the fromStoryFullId
fromStoryFullId can not pass null

final result = await client.send(td.SendStory(
      chatId: chatId,
      content: input,
      privacySettings: const td.StoryPrivacySettingsEveryone(exceptUserIds: []),
      activePeriod: 86400,
      fromStoryFullId: const td.StoryFullId(senderChatId: 0, storyId: 0),
      isPostedToChatPage: false,
      protectContent: true,
    ));

I deal with the error like this: Story to repost not found, please help me, thanks

**Comment by stellarNuke** [comment]
> Story to repost not found

I thing you need to first get _storyId_ and _senderChatId_ using **td.GetStory()** method then pass  _senderChatId_ and _storyId_  to the **td.storyFullId()**
