### ISSUE TITLE
Bug: type 'int' is not a subtype of type 'double' on self_destruct_in

### ISSUE THREAD

**Issue by AndrewTran2018** [ivk1800/tdlib-dart#3]
type 'int' is not a subtype of type 'double'
E/flutter ( 6346): #0      Message.fromJson (package:tdlib/src/api/objects/message.dart:242:27)
E/flutter ( 6346): #1      ConvertExtensions.toTdObject (package:tdlib/src/api/extensions/convert_extensions.dart:1

**Comment by AndrewTran2018** [comment]
There are still a lot of bugs related to number conversion including int and double like this one. I fixed some, but to ensure its reliability please recheck and improve your code generator. I'm sick of these kinds of issues

**Comment by AndrewTran2018** [comment]
@ivk1800

**Comment by ivk1800** [comment]
There are steps to reproduce? selfDestructIn(self_destruct_in) is double in [td_api.tl](https://github.com/tdlib/td/blob/c95598e5e1493881d31211c1329bdbe4630f6136/td/generate/scheme/td_api.tl#L1137)

What is value of `selfDestructIn` ? can you provider json example of message object?

**Comment by AndrewTran2018** [comment]
> There are steps to reproduce? selfDestructIn(self_destruct_in) is double in [td_api.tl](https://github.com/tdlib/td/blob/c95598e5e1493881d31211c1329bdbe4630f6136/td/generate/scheme/td_api.tl#L1137)
> 
> What is value of `selfDestructIn` ? can you provider json example of message object

selfDetructIn is int in this case. That's why the line : selfDestructIn: json['self_destruct_in'] causes a crash.

**Comment by ivk1800** [comment]
Fixed https://github.com/ivk1800/tdlib-dart/commit/d5ed66a6f32ef57a0047ab4610359b1eb3b45b25
