### ISSUE TITLE
type 'int' is not a subtype of type 'double': autoDeleteIn: json['auto_delete_in']

### ISSUE THREAD

**Issue by AndrewTran2018** [ivk1800/tdlib-dart#6]
type 'int' is not a subtype of type 'double'
E/flutter ( 6346): #0 Message.fromJson (package:tdlib/src/api/objects/message.dart:243:27)
E/flutter ( 6346): https://github.com/ivk1800/tdlib-dart/issues/1 ConvertExtensions.toTdObject (package:tdlib/src/api/extensions/convert_extensions.dart:1

@ivk1800

**Comment by ivk1800** [comment]
you are using the old version, please pull actual master.
