### ISSUE TITLE
how to  generated schema classes in dart?

### ISSUE THREAD

**Issue by touchmanyfish** [ivk1800/tdlib-dart#7]
hello!amazing work!  
  
Is there any way to  generated [schema classes](https://github.com/ivk1800/tdlib-dart/tree/master/lib/src/api/objects) of [td_api.tl](https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl) in dart?

**Comment by ivk1800** [comment]
Generator is currently private.
